before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: binary
    main: ./cmd/ansible-operator/
    binary: ansible-operator
    asmflags: "{{ .Env.GO_BUILD_ASMFLAGS }}"
    gcflags: "{{ .Env.GO_BUILD_GCFLAGS }}"
    ldflags: "{{ .Env.GO_BUILD_LDFLAGS }}"
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
    - linux
    goarch:
    - amd64
    - arm64
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
changelog:
  use: github-native
  skip: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
release:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
